version: '3.8'

services:
  planning-poker:
    build: .
    ports:
      - "3000:3000"  # Frontend
      - "3001:3001"  # Socket server
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SOCKET_PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s